# Generated by Django 4.2.7 on 2025-07-20 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_admin_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD 형식으로 입력하세요.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '남성'), ('female', '여성'), ('other', '기타')], help_text='성별을 선택하세요.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='한글 또는 영문으로 2자 이상 입력하세요.', max_length=100, validators=[django.core.validators.RegexValidator(message='이름은 한글과 영문만 입력 가능합니다.', regex='^[가-힣a-zA-Z\\s]+$'), django.core.validators.MinLengthValidator(2, message='이름은 2자 이상이어야 합니다.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='010-1234-5678 형식으로 입력하세요.', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='올바른 전화번호 형식을 입력해주세요. (예: 010-1234-5678)', regex='^010-\\d{3,4}-\\d{4}$')]),
        ),
    ]
